---
triple:          'arm64-apple-darwin'
binary-path:     '/Users/marekfort/Library/Developer/Xcode/DerivedData/App-dfsuypgsncvyyvfzhqgemutcjgrv/Build/Intermediates.noindex/ArchiveIntermediates/App/InstallationBuildProductsLocation/Applications/App.app/App'
relocations:     []
...
