version: 2.1

executors:
  macos-executor:
    macos:
      xcode: "14.3.1"
    working_directory: ~/project

jobs:
  inspect_bundle:
    executor: macos-executor
    steps:
      - checkout
      - run:
          name: Inspect bundle
          command: |
            curl https://mise.run | sh
            export PATH="$HOME/.local/bin:$PATH"
            mise activate bash
            mise install
            mise exec -- tuist inspect bundle App.xcarchive --json
workflows:
  inspect:
    jobs:
      - inspect_bundle
