version: 2.1

executors:
  macos-executor:
    macos:
      xcode: "16.3.0"
    working_directory: ~/project

jobs:
  inspect_bundle:
    executor: macos-executor
    steps:
      - checkout
      - run:
          name: Download App.ipa from GitHub Releases
          command: |
            curl -L -o App.ipa https://github.com/tuist/tuist/releases/download/4.52.0/App.ipa
      - run:
          name: Verify App.ipa download
          command: |
            ls -la App.ipa
            file App.ipa
      - run:
          name: Inspect bundle
          command: |
            ./tuist-cli inspect bundle fixtures/ios_app_with_frameworks/App.ipa --json
            ./tuist-cli inspect bundle App.ipa --json

workflows:
  inspect:
    jobs:
      - inspect_bundle
