version: 2.1

executors:
  macos-executor:
    macos:
      xcode: "14.3.1"
    working_directory: ~/project

jobs:
  inspect_bundle:
    executor: macos-executor
    steps:
      - checkout
      - run:
          name: Install mise
          command: |
            curl https://mise.run | sh
            export PATH="$HOME/.local/bin:$PATH"
            mise activate
            mise doctor
      - run:
          name: Install Tuist via mise
          command: |
            mise install
      - run:
          name: Inspect Bundle
          command: |
            # mise sh automatically sets up the environment for installed tools
            mise exec -- tuist inspect bundle App.xcarchive --json

workflows:
  inspect:
    jobs:
      - inspect_bundle
